// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRe6IAq6XhjNDpBUEndhUGngfBAJdbAjQ',
    appId: '1:271311148357:web:95dca011d3b26775bc1a2c',
    messagingSenderId: '271311148357',
    projectId: 'reviewbook-e675a',
    authDomain: 'reviewbook-e675a.firebaseapp.com',
    storageBucket: 'reviewbook-e675a.appspot.com',
    measurementId: 'G-9YN9EZ0YHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa5A8Asfpl0dArcxhLnJS6gdJiA_fAxUA',
    appId: '1:271311148357:android:116e636330915d72bc1a2c',
    messagingSenderId: '271311148357',
    projectId: 'reviewbook-e675a',
    storageBucket: 'reviewbook-e675a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByZ28y1hZLHzwzKJv-PruyRc-64GC-3Zk',
    appId: '1:271311148357:ios:246d1f24b1c625cfbc1a2c',
    messagingSenderId: '271311148357',
    projectId: 'reviewbook-e675a',
    storageBucket: 'reviewbook-e675a.appspot.com',
    iosClientId: '271311148357-qngcs4aktd7dblpng2kut3qmtkji8kpa.apps.googleusercontent.com',
    iosBundleId: 'com.sudarlife.reviewBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByZ28y1hZLHzwzKJv-PruyRc-64GC-3Zk',
    appId: '1:271311148357:ios:e88b9dc3f498be3ebc1a2c',
    messagingSenderId: '271311148357',
    projectId: 'reviewbook-e675a',
    storageBucket: 'reviewbook-e675a.appspot.com',
    iosClientId: '271311148357-e8hgi6ir1maut6mu3raib2139048k8j6.apps.googleusercontent.com',
    iosBundleId: 'com.example.reviewBook.RunnerTests',
  );
}
